// assemble.js - The Project Assembler
const fs = require('fs');
const path = require('path');

const ROOT_DIR = __dirname;
const ASSEMBLE_DIR = path.join(ROOT_DIR, 'assemble');

// Ensure assemble directory exists
if (!fs.existsSync(ASSEMBLE_DIR)) {
    fs.mkdirSync(ASSEMBLE_DIR, { recursive: true });
}

console.log("🏗️ Starting Assembly Process...");

// 1. Select Project to Assemble
const projects = fs.readdirSync(ROOT_DIR).filter(file => {
    return fs.statSync(path.join(ROOT_DIR, file)).isDirectory() && file !== 'assemble' && file !== 'node_modules';
});

if (projects.length === 0) {
    console.log("⚠️ No project folders found to assemble.");
    process.exit(1);
}

console.log("📁 Available Projects to Assemble:");
projects.forEach((p, i) => console.log(`   ${i + 1}. ${p}`));

// For simplicity, let's just assemble the first one or ask user. 
// Let's automate it to assemble ALL projects into the 'assemble' folder for now.
// Or you can modify this to pick one. Let's pick 'project1' as default for this hint.

const TARGET_PROJECT = 'project1'; // Change this to the folder you want to assemble
const PROJECT_PATH = path.join(ROOT_DIR, TARGET_PROJECT);

if (!fs.existsSync(PROJECT_PATH)) {
    console.log(`❌ Project '${TARGET_PROJECT}' not found.`);
    process.exit(1);
}

console.log(`\n🚀 Assembling project: ${TARGET_PROJECT}`);

try {
    const htmlPath = path.join(PROJECT_PATH, 'index.html');
    const cssPath = path.join(PROJECT_PATH, 'style.css');
    const jsPath = path.join(PROJECT_PATH, 'game.js');

    let htmlContent = fs.existsSync(htmlPath) ? fs.readFileSync(htmlPath, 'utf8') : '<!-- No HTML found -->';
    let cssContent = fs.existsSync(cssPath) ? fs.readFileSync(cssPath, 'utf8') : '/* No CSS found */';
    let jsContent = fs.existsSync(jsPath) ? fs.readFileSync(jsPath, 'utf8') : '// No JS found';

    console.log("✅ Files loaded.");

    // 2. Assemble Option A: Single HTML File (Embedding CSS/JS)
    const finalHtml = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Assembled ${TARGET_PROJECT}</title>
    <style>
        ${cssContent}
    </style>
</head>
<body>
    ${htmlContent.replace(/<html[^>]*>|<\/html>|<head[^>]*>.*<\/head>|<body[^>]*>|<\/body>/gis, '')}
    
    <script>
        ${jsContent}
    </script>
    
    <hr>
    <p><em>Generated by Supreme Master Agent | Assembled on ${new Date().toLocaleString()}</em></p>
</body>
</html>
    `.trim();

    // 3. Write Final Output
    const outputPath = path.join(ASSEMBLE_DIR, `${TARGET_PROJECT}_final.html`);
    fs.writeFileSync(outputPath, finalHtml);
    console.log(`✅ Assembled HTML saved to: assemble/${TARGET_PROJECT}_final.html`);

    console.log("🎉 Assembly Complete! Check the 'assemble' folder.");

} catch (err) {
    console.error("❌ Assembly Failed:", err.message);
}